package org.firstinspires.ftc.teamcode.opmodes.util;

// Regular
public enum AutoState {
    MOVE_TO_FIRST_NEUTRAL_SAMPLE,
    PUSH_FIRST_NEUTRAL_SAMPLE,
    CHECK_FIRST_SAMPLE_FINISHED,
    MOVE_TO_SECOND_NEUTRAL_SAMPLE,
    PUSH_SECOND_NEUTRAL_SAMPLE,
    CHECK_SECOND_SAMPLE_FINISHED,
    MOVE_TO_THIRD_NEUTRAL_SAMPLE,
    PUSH_THIRD_NEUTRAL_SAMPLE,
    CHECK_THIRD_SAMPLE_FINISHED,
    MOVE_TO_OBSERVATION_ZONE,
    COMPLETE

}
